# Generated by Django 4.2.28 on 2026-02-20 05:09

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('queued', 'En cola'), ('generating', 'Generando clips'), ('concat', 'Ensamblando'), ('done', 'Listo'), ('error', 'Error')], default='draft', max_length=20)),
                ('prompt', models.TextField(blank=True, verbose_name='Prompt')),
                ('transition', models.CharField(choices=[('crossfade', '✨ Crossfade suave'), ('fade_black', '⬛ Fundido a negro'), ('wipe_right', '➡️ Barrido'), ('zoom_blur', '🔍 Zoom blur')], default='crossfade', max_length=20, verbose_name='Transición')),
                ('ai_model', models.CharField(default='sora-2', max_length=100, verbose_name='Modelo IA')),
                ('music_choice', models.CharField(choices=[('cinematic', '🎼 Cinemático'), ('upbeat', '🎵 Inspiracional'), ('luxury', '🎹 Lujo'), ('upload', '📤 Mi música'), ('none', '🔇 Sin música')], default='cinematic', max_length=100, verbose_name='Música')),
                ('music_file', models.FileField(blank=True, null=True, upload_to=core.models.music_path, verbose_name='Mi música')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_msg', models.CharField(blank=True, max_length=500)),
                ('error_msg', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.img_path, verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0)),
                ('clip_status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20)),
                ('clip_file', models.FileField(blank=True, null=True, upload_to='clips/', verbose_name='Clip')),
                ('clip_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.videoproject')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
